In [0]:
import torch

In [0]:
t = torch.tensor([[1,2,3], [1,2,2]])

In [0]:
if torch.cuda.is_available():
    t = t.cuda()
t

tensor([[1, 2, 3],
        [1, 2, 2]], device='cuda:0')

In [0]:
t.shape

torch.Size([2, 3])

In [0]:
len(t.shape)

2

In [0]:
t.reshape(1,6)

tensor([[1, 2, 3, 1, 2, 2]], device='cuda:0')

In [0]:
t.reshape(3,2)

tensor([[1, 2],
        [3, 1],
        [2, 2]], device='cuda:0')